"""ip_address nullable=false

Revision ID: 25450b29392e
Revises: 36fe64737bef
Create Date: 2024-03-29 15:34:43.033562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25450b29392e'
down_revision = '36fe64737bef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_token', 'ip_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_token', 'ip_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
