"""renamed user_word_id to bundle_id in user_words db

Revision ID: 2b894ec3ede3
Revises: ae7b49ca58d8
Create Date: 2024-03-25 20:18:24.146480

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b894ec3ede3'
down_revision = 'ae7b49ca58d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_words', sa.Column('bundle_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_column('user_words', 'user_word_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_words', sa.Column('user_word_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_column('user_words', 'bundle_id')
    # ### end Alembic commands ###
