"""hz

Revision ID: 36fe64737bef
Revises: 542da20ce2d2
Create Date: 2024-03-29 15:23:29.655102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36fe64737bef'
down_revision = '542da20ce2d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('ip_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_token', 'ip_address')
    # ### end Alembic commands ###
