"""comment

Revision ID: 445cfcb3c75c
Revises: 25450b29392e
Create Date: 2024-06-17 02:37:22.770521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445cfcb3c75c'
down_revision = '25450b29392e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_and_word_and_translation_id', 'user_words', ['user_id', 'word_id', 'translation_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_and_word_and_translation_id', 'user_words', type_='unique')
    # ### end Alembic commands ###
