"""set unique user_id to refresh token table

Revision ID: 542da20ce2d2
Revises: 6e4e5182d598
Create Date: 2024-03-27 18:54:51.992970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542da20ce2d2'
down_revision = '6e4e5182d598'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'refresh_token', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_token', type_='unique')
    # ### end Alembic commands ###
