"""added column pos to translation table 

Revision ID: ae7b49ca58d8
Revises: ed68769e4df0
Create Date: 2024-03-25 14:27:08.457053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae7b49ca58d8'
down_revision = 'ed68769e4df0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation', sa.Column('pos', sa.String(), nullable=True))
    op.alter_column('translation', 'translation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('translation', 'translation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('translation', 'pos')
    # ### end Alembic commands ###
