"""introduced a ban on non-uniqueness word_id with translation

Revision ID: b6dd4e029df8
Revises: 2b894ec3ede3
Create Date: 2024-03-25 21:11:30.991681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6dd4e029df8'
down_revision = '2b894ec3ede3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_word_id_and_translation', 'translation', ['word_id', 'translation'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_word_id_and_translation', 'translation', type_='unique')
    # ### end Alembic commands ###
