"""created database

Revision ID: ed68769e4df0
Revises: 
Create Date: 2024-03-23 19:37:25.119138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed68769e4df0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('word_base',
    sa.Column('word_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('word_id'),
    sa.UniqueConstraint('word')
    )
    op.create_table('translation',
    sa.Column('translation_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('word_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('translation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['word_base.word_id'], ),
    sa.PrimaryKeyConstraint('translation_id')
    )
    op.create_table('user_words',
    sa.Column('user_word_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('word_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('translation_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('added_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['translation_id'], ['translation.translation_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word_base.word_id'], ),
    sa.PrimaryKeyConstraint('user_word_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_words')
    op.drop_table('translation')
    op.drop_table('word_base')
    op.drop_table('users')
    # ### end Alembic commands ###
